"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
APP_NAME = "JeFaPaTo"
DATA_FILES = ["frontend", "jefapato", "examples"]
OPTIONS = {
    "iconfile": "frontend/assets/icons/icon.icns",
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "Jena Facial Palsy Tool",
        'CFBundleIdentifier': "com.cvgj.osx.jefapato",
        'CFBundleVersion': "1.0.0",
        'CFBundleShortVersionString': "1.0.0",
        'NSHumanReadableCopyright': u"Copyright © 2023, Tim Büchner, All Rights Reserved",
        # 'NSCameraUsageDescription': u'JeFaPaTo needs access to your camera to record videos.',
        'LSPrefersPPC': False,
    },
    "alias": False,
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
