"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
APP_NAME = "JeFaPaTo"
DATA_FILES = ["frontend", "jefapato"]
OPTIONS = {
    "iconfile": "frontend/assets/icons/icon.icns",
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "Jena Facial Palsy Tool",
        'CFBundleIdentifier': "com.cvgj.osx.jefapato",
        'CFBundleVersion': "0.1.0",
        'CFBundleShortVersionString': "0.1.0",
        'NSHumanReadableCopyright': u"Copyright © 2023, Tim Büchner, All Rights Reserved"
    },
    "alias": False,
    "arch": "arm64",
    "frameworks": [
        '/Users/buechner/miniconda3/envs/jefapato/lib/libffi.8.dylib'
    ],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
